version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: corona-symfony-app_nginx
    volumes:
      - ./:/var/www/backend-api
      - ./services/frontend-app:/var/www/frontend-app
      - ./services/admin-app:/var/www/admin-app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - "corona.test"
          - "corona-api.test"

  mysql:
    image: mariadb:10.5.10
    container_name: corona-symfony-app_mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=app
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "4406:3306"

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - PHP_VERSION=8.0
    container_name: corona-symfony-app_php-fpm
    environment:
      - PHP_IDE_CONFIG=serverName=coronaApp
    volumes:
      - ./:/var/www/backend-api
      - ./services/frontend-app:/var/www/frontend-app
      - ./services/admin-app:/var/www/admin-app
    restart: always
    networks:
      default:
        aliases:
          - "corona.test"
          - "corona-api.test"

  mailhog:
    image: mailhog/mailhog
    container_name: corona-symfony-app_mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      default:
        aliases:
          - "corona.test"
          - "corona-api.test"

volumes:
  mysql-data:
    external: false
    name: corona-symfony-app_mysql-data