name: PHPUnit Test
on: [ push, pull_request ]

jobs:
  phpunit:
    name: "PHPUnit with PHP ${{ matrix.php-versions }}"
    runs-on: ubuntu-latest
    container: ugurkankya/php${{ matrix.php-versions }}-fpm
    strategy:
      matrix:
        php-versions: [ '8.0' ]
    env:
      KERNEL_CLASS: 'App\Kernel'
      APP_ENV: test
      APP_SECRET: testSecret
      DATABASE_URL: mysql://root:app@mysql:3306/app?serverVersion=10.5.10-MariaDB
      JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
      JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
      JWT_PASSPHRASE: testJwtPassphrase
      CONTEXT_YEAR: 2022
      CONTEXT_RELEASE_VERSION: 0.1.1
      CONTEXT_MAIL_SENDER: noreply@corona.test
      CONTEXT_FRONTEND_URL: http://localhost:8080

    services:
      mysql:
        image: mariadb:10.5.10
        env:
          MYSQL_ROOT_PASSWORD: app
          MYSQL_DATABASE: app

    steps:
      - name: Clone API
        uses: actions/checkout@v3

      - name: Install Composer Dependencies
        run: composer install

      - name: Create Database
        run: bin/console doctrine:database:create --no-interaction

      - name: Migrate Migrations
        run: bin/console doctrine:migrations:migrate --no-interaction

      - name: Validate Doctrine Schema
        run: bin/console doctrine:schema:validate

      - name: Generate JWT Keys
        run: bin/console lexik:jwt:generate-keypair

      - name: Check JWT Config
        run: bin/console lexik:jwt:check-config

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit